version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/app/step3/zip/
    overwrite: yes

permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user

hooks:
  AfterInstall:
    - location: stop.sh # Close Spring Boot that is not connected to Nginx.
      timeout: 60
      runas: ec2-user
  ApplicationStart:
    - location: start.sh # Start a new version of Spring Boot with a port that is not connected to Nginx.
      timeout: 60
      runas: ec2-user
  ValidateService:
    - location: health.sh # Check that the new spring boot is running normally.
      timeout: 60
      runas: ec2-user
